# Generated by Django 5.1.6 on 2025-03-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='img_link',
        ),
        migrations.AddField(
            model_name='listings',
            name='img_file',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
