# Generated by Django 5.1.6 on 2025-03-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listings_img_link_listings_img_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['category']},
        ),
    ]
