# Generated by Django 5.1.6 on 2025-03-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_user_postal_code_remove_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_on_watchlist',
            field=models.CharField(default='', max_length=8),
        ),
    ]
