# Generated by Django 5.1.6 on 2025-03-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_user_number_on_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='categories',
            field=models.ManyToManyField(related_name='listed', to='auctions.categories'),
        ),
    ]
